Harness Status: OK
Found 24 tests: Pass = 9 Fail = 15
Pass name  
Pass length  
Pass No arguments  
Pass Calling  
Fail Invalid descriptor argument  assert_throws: new Memory(object "[object Object]") function "() => new WebAssembly.Memory(invalidArgument)" did not throw
Fail Undefined initial value in descriptor  assert_throws: function "() => new WebAssembly.Memory({ "initial": undefined })" did not throw
Fail Out-of-range initial value in descriptor: NaN  assert_throws: function "() => new WebAssembly.Memory({ "initial": value })" did not throw
Fail Out-of-range maximum value in descriptor: NaN  assert_throws: function "() => new WebAssembly.Memory({ "initial": 0, "maximum": value })" did not throw
Fail Out-of-range initial value in descriptor: Infinity  assert_throws: function "() => new WebAssembly.Memory({ "initial": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range maximum value in descriptor: Infinity  assert_throws: function "() => new WebAssembly.Memory({ "initial": 0, "maximum": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range initial value in descriptor: -Infinity  assert_throws: function "() => new WebAssembly.Memory({ "initial": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range maximum value in descriptor: -Infinity  assert_throws: function "() => new WebAssembly.Memory({ "initial": 0, "maximum": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range initial value in descriptor: -1  assert_throws: function "() => new WebAssembly.Memory({ "initial": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range maximum value in descriptor: -1  assert_throws: function "() => new WebAssembly.Memory({ "initial": 0, "maximum": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range initial value in descriptor: 4294967296  assert_throws: function "() => new WebAssembly.Memory({ "initial": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range maximum value in descriptor: 4294967296  assert_throws: function "() => new WebAssembly.Memory({ "initial": 0, "maximum": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range initial value in descriptor: 68719476736  assert_throws: function "() => new WebAssembly.Memory({ "initial": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Fail Out-of-range maximum value in descriptor: 68719476736  assert_throws: function "() => new WebAssembly.Memory({ "initial": 0, "maximum": value })" threw object "RangeError: argument out of range" ("RangeError") expected object "TypeError" ("TypeError")
Pass Initial value exceeds maximum  
Fail Proxy descriptor  assert_unreached: Should not call [[HasProperty]] with maximum Reached unreachable code
Pass Order of evaluation for descriptor  
Pass Zero initial  
Pass Non-zero initial  
Pass Stray argument  
